### ISSUE TITLE
53 sites?

### ISSUE THREAD

**Issue by kfpbennett** [bsevansunc/birdCats#4]
I realized that STUR is in class 30. Which means based on the method I used to select sites (as many as possible for higher end, 10 sites for lower end), that should mean 53 sites. Is it worth it to mess with the code to try to swing that, or would it not be scrutinized if I dropped a 20% site to keep it at 52?

**Comment by bsevansunc** [comment]
How would that be on the scheduling end? If it isn't too many, it would be easy enough to rewrite the code for 53 sites rather than 52.

**Comment by kfpbennett** [comment]
It would not be a major problem to add one site per month. I would just have to pick a week to do 14.
